name: Actualizar eventos JSON

on:
  schedule:
    - cron: '*/5 * * * *' # Ejecuta cada 5 minutos

jobs:
  actualizar_json:
    runs-on: ubuntu-latest
    steps:
      - name: Checar el repositorio
        uses: actions/checkout@v2

      - name: Configurar Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.5'

      - name: Instalar dependencias
        run: |
          pip install requests beautifulsoup4

      - name: Mostrar contenido de eventos.json antes de ejecutar el script
        run: cat agenda_pro/eventos.json

      - name: Ejecutar el script Python
        run: |
          python agenda_pro/eventos.py

      - name: Mostrar contenido de eventos.json después de ejecutar el script
        run: cat agenda_pro/eventos.json

      - name: Configurar credenciales de GitHub
        run: |
          git config --local user.email "lirikablazfema@gmail.com"
          git config --local user.name "Luis Olv"
          
      - name: Realizar pull antes de push
        run: |
          git pull origin main || echo "No se pudo hacer pull"

      - name: Subir archivo actualizado
        run: |
          # Agregar archivos modificados
          git add -A
          
          # Forzar commit aunque los cambios sean triviales
          git commit --allow-empty -m "Actualización de eventos JSON" || echo "No hay cambios para hacer commit"
          
          # Empujar los cambios
          git push || echo "No se pudo hacer push"
