name: Actualizar eventos JSON

on:
  workflow_dispatch:

jobs:
  actualizar_json:
    runs-on: ubuntu-latest

    steps:
    - name: Checar repositorio
      uses: actions/checkout@v2

    - name: Configurar Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Instalar dependencias
      run: |
        pip install requests beautifulsoup4

    - name: Mostrar contenido de eventos.json antes de ejecutar el script
      run: cat agenda_pro/eventos.json

    - name: Ejecutar el script Python
      run: python agenda_pro/eventos.py

    - name: Mostrar contenido de eventos.json después de ejecutar el script
      run: cat agenda_pro/eventos.json

    - name: Subir archivo actualizado
      run: |
        git config --local user.email "lirikablazfema@gmail.com"
        git config --local user.name "AguilaAzulcrema"
        git pull origin main  # Agregar este comando para hacer pull
        git add agenda_pro/eventos.json
        git commit -m "Actualización de eventos JSON"
        git push origin main
